CREATE DATABASE ExAula02

USE ExAula02

CREATE TABLE Produto(
Codigo INT PRIMARY KEY NOT NULL,
Descriçao VARCHAR(50),
Fornecedor_prod FOREIGN KEY NOT NULL,
Preço DECIMAL(7,2)
)

CREATE TABLE Venda(
Codigo INT PRIMARY KEY NOT NULL,
Codigo_venda FOREIGN KEY NOT NULL,
Cliente_venda FOREIGN KEY NOT NULL,
Qtd INT,
Data_venda DATETIME
)

CREATE TABLE Fornecedor(
ID INT PRIMARY KEY NOT NULL,
Nome VARCHAR(50),
Logradouro VARCHAR(100),
Numero INT NOT NULL,
Complemento VARCHAR(30),
Cidade VARCHAR(70)
)

CREATE TABLE Cliente(
CPF CHAR(11) PRIMARY KEY NOT NULL,
Nome VARCHAR(50),
Telefone VARCHAR(9)
)